# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(780, 504)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.remove_all = QtWidgets.QPushButton(self.centralwidget)
        self.remove_all.setGeometry(QtCore.QRect(10, 320, 121, 41))
        self.remove_all.setObjectName("remove_all")
        self.remove_one = QtWidgets.QPushButton(self.centralwidget)
        self.remove_one.setGeometry(QtCore.QRect(140, 320, 121, 41))
        self.remove_one.setObjectName("remove_one")
        self.add_1 = QtWidgets.QPushButton(self.centralwidget)
        self.add_1.setGeometry(QtCore.QRect(270, 320, 121, 41))
        self.add_1.setObjectName("add_1")
        self.add_to_list = QtWidgets.QPushButton(self.centralwidget)
        self.add_to_list.setGeometry(QtCore.QRect(595, 320, 181, 41))
        self.add_to_list.setObjectName("add_to_list")
        self.search = QtWidgets.QPushButton(self.centralwidget)
        self.search.setEnabled(True)
        self.search.setGeometry(QtCore.QRect(405, 320, 181, 41))
        self.search.setObjectName("search")
        self.status_bar = QtWidgets.QLabel(self.centralwidget)
        self.status_bar.setGeometry(QtCore.QRect(410, 370, 361, 21))
        self.status_bar.setObjectName("status_bar")
        self.text_list_of_products = QtWidgets.QLabel(self.centralwidget)
        self.text_list_of_products.setGeometry(QtCore.QRect(16, 12, 371, 16))
        self.text_list_of_products.setObjectName("text_list_of_products")
        self.lenta = QtWidgets.QPushButton(self.centralwidget)
        self.lenta.setGeometry(QtCore.QRect(405, 400, 121, 41))
        self.lenta.setObjectName("lenta")
        self.perekrestok = QtWidgets.QPushButton(self.centralwidget)
        self.perekrestok.setGeometry(QtCore.QRect(530, 400, 121, 41))
        self.perekrestok.setObjectName("perekrestok")
        self.magnit = QtWidgets.QPushButton(self.centralwidget)
        self.magnit.setGeometry(QtCore.QRect(655, 400, 121, 41))
        self.magnit.setObjectName("magnit")
        self.text_summ_cost = QtWidgets.QLabel(self.centralwidget)
        self.text_summ_cost.setGeometry(QtCore.QRect(20, 370, 371, 21))
        self.text_summ_cost.setObjectName("text_summ_cost")
        self.summ_cost = QtWidgets.QLCDNumber(self.centralwidget)
        self.summ_cost.setGeometry(QtCore.QRect(10, 400, 381, 41))
        self.summ_cost.setObjectName("summ_cost")
        self.browser = QtWidgets.QPushButton(self.centralwidget)
        self.browser.setGeometry(QtCore.QRect(620, 10, 151, 25))
        self.browser.setObjectName("browser")
        self.save_as_txt = QtWidgets.QPushButton(self.centralwidget)
        self.save_as_txt.setGeometry(QtCore.QRect(10, 450, 241, 31))
        self.save_as_txt.setObjectName("save_as_txt")
        self.load_bd = QtWidgets.QPushButton(self.centralwidget)
        self.load_bd.setGeometry(QtCore.QRect(535, 450, 241, 31))
        self.load_bd.setObjectName("load_bd")
        self.save_as_bd = QtWidgets.QPushButton(self.centralwidget)
        self.save_as_bd.setGeometry(QtCore.QRect(270, 450, 251, 31))
        self.save_as_bd.setObjectName("save_as_bd")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(15, 40, 376, 271))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_2.setGeometry(QtCore.QRect(410, 40, 361, 271))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.search_enter = QtWidgets.QTextEdit(self.centralwidget)
        self.search_enter.setGeometry(QtCore.QRect(410, 10, 201, 24))
        self.search_enter.setObjectName("search_enter")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.remove_all.setText(_translate("MainWindow", "remove all products"))
        self.remove_one.setText(_translate("MainWindow", "remove one product"))
        self.add_1.setText(_translate("MainWindow", "add one product"))
        self.add_to_list.setText(_translate("MainWindow", "add product to cart"))
        self.search.setText(_translate("MainWindow", "search product in shop"))
        self.status_bar.setText(_translate("MainWindow", "TextLabel"))
        self.text_list_of_products.setText(_translate("MainWindow", "list of products to buy"))
        self.lenta.setText(_translate("MainWindow", "lenta"))
        self.perekrestok.setText(_translate("MainWindow", "perekrestok"))
        self.magnit.setText(_translate("MainWindow", "magnit"))
        self.text_summ_cost.setText(_translate("MainWindow", "summary cost in shop"))
        self.browser.setText(_translate("MainWindow", "search in browser"))
        self.save_as_txt.setText(_translate("MainWindow", "save as txt file"))
        self.load_bd.setText(_translate("MainWindow", "load database"))
        self.save_as_bd.setText(_translate("MainWindow", "save as database"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
